# Fruit = input("Enter your favorite fruits separated by spaces: ")
# print(Fruit)
# print(type(Fruit))
# Fruits = input("Enter your favorite fruits separated by spaces: ").split()
# print(Fruits)
# print(type(Fruits))
# num = input("Enter a number: ").split()
# print(num)
# print(type(num))
numbers = list(map(int, input("Enter three numbers separated by spaces:").split()))
print(numbers)
print(type(numbers))
